services:
  cv-builder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv-builder
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./data:/app/data
